### ISSUE TITLE
Unable to find project in organisation list

### ISSUE THREAD

**Issue by vitalbone** [getsentry/sentry-wizard#104]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`"@sentry/nextjs": "^6.3.0"`

### Steps to Reproduce

```
npx @sentry/wizard -i nextjs

? Please select your project in Sentry:
```

### Expected Result

My project is in the list and I am able to select it.

### Actual Result

My project is not in the list and I am unable to select it.

Is there a limit to the amount of projects the list can render? We have ~67 projects associated with our organisation.

**Comment by rhcarvalho** [comment]
Currently the wizard fetches only at most 50 projects.

(Ref: https://github.com/getsentry/sentry/blob/3e0a0bf980e238fe544e2b4151eb6cf9cf94f9ee/src/sentry/web/frontend/setup_wizard.py#L45-L47)

**Comment by talha-masood22** [comment]
Facing the same issue

**Comment by daiger14** [comment]
Same for our project

**Comment by MagnusHJensen** [comment]
Same for our organization

**Comment by Lms24** [comment]
Hi, the 50 projects limit was fixed a while ago in the Sentry backend: https://github.com/getsentry/sentry/pull/52093

I'm gonna close this because afaict, the original issue is resolved. 

@MagnusHJensen since you commented recently here, would you mind giving this a try again? Or are you by any chance on self-hosted Sentry? Then the fix in your version might not be in your self-hosted version yet.

**Comment by MagnusHJensen** [comment]
We are using a self-hosted version, @Lms24 mind giving me the version number in which this fix was introduced? Then I can report that back to the guys who own this.
