### ISSUE TITLE
[Next.js] Project selection list is too large for terminal.

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-wizard#286]
When having an account with a lot of projects, the list is too large to be properly displayed in the terminal and scrolling is also messed up.

We probably need to fix this upstream in clack.

**Comment by tmikoss** [comment]
If I can add my two cents, I'd like to see some kind of search functionality for that list, to help narrow it down. With access to multiple large organizations, even a properly functioning scrollable list is not ideal. When using the wizard, I have an idea what project I want to link with, and couple keystrokes in a search function could narrow the list down considerably.

Alternatively, in my particular case "I'll add the DSN via env variables" option would be the best - if the wizard fetches and inserts DSN as a string, I will replace it with a configurable value anyway, because I want as many integration options as possible to be configurable without re-building the application.

**Comment by mitsuhiko** [comment]
I wonder if it wouldn’t be better to bring up that part of the UI in the browser rather than the terminal.
