### ISSUE TITLE
react-native wizard telemetry

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-wizard#365]
To ensure we can track that the wizard is working well, and so that we can identify patterns we want to collect some telemetry data from the wizard. This will also allow us to get insights to improve the DX of the wizard flow

Example tags: 
Does not need to be limited to this

  "tags": [
    ["added-env-var-to-ci", "True"],
    ["already-has-sentry-account", "True"],
    ["environment", "production"],
    ["has-promo-code", "False"],
    ["initial-sdk-version", ">=7.47.0"],
    ["integration", "sourcemaps"],
    ["level", "info"],
    ["node", "v16.14.2"],
    ["opened-wizard-link", "True"],
    ["platform", "win32"],
    ["project", "portal-frontend"],
    ["runtime", "node v16.14.2"],
    ["runtime.name", "node"],
    ["selected-tool", "webpack"],
    ["self-hosted", "False"],
    ["release", "3.5.0"],
    ["user", "id:offerfit"],
    ["transaction", "sentry-wizard-execution"],
    ["url", "https://sentry.io/"]
  

See the [Sentry Wizard Dashboard](https://sentry.sentry.io/dashboard/53706/?project=4505425820712960&query=wizard&statsPeriod=14d) for more insights

We are not interested in collecting any PII about the individual users! Please check existing implementation for best practices 🙏

**Comment by kahest** [comment]
related item in iOS: https://github.com/getsentry/sentry-wizard/issues/343

**Comment by Lms24** [comment]
I was playing a little with how we could use our `withTelemetry` helper in the older, class-based wizards, like RN. There are a couple of problems:

* Since some steps that seemingly belong to the ReactNative step happen before (e.g. platform selection and project selection via login), we can't easily track them with the callback-based `withTelemetry` helper.
* In the simplest form, add the wrapper around the logic in the the `emit` hook. In addition to missing the steps above, everything triggered from `shouldConfigure` also won't be caught. Maybe still worth a trade-off...
  * Given above, users are well into the flow before we can notify them that we collect telemetry. For instance by then, they'll already have logged in.
* Generally, we don't seem to handle SIGINT/Cmd+C interrupts at all in the old flows. Meaning, as soon as someone cancels the wizard, the (at this point still running) transaction won't be sent to Sentry. In the `clack`-based, new flows, we already handle this via `abortIfCancelled` and we'd probably need a similar logic here.

All in all, not sure if it's even worth adding half-baked telemetry here. IMO this is a good reason to rewrite the class-based wizards where we wouldn't face any of these problems.

**Comment by krystofwoldrich** [comment]
https://github.com/getsentry/sentry-wizard/pull/477
