### ISSUE TITLE
Should give the option to use npm install --force if necessary

### ISSUE THREAD

**Issue by windmillcode0** [getsentry/sentry-wizard#522]
### Environment

What version are you running? Etc.
7.56.0

### Steps to Reproduce

1. Create a new angular 17 project
2. install ng-hcaptcha with force  because its incompabtiable in the semver but still works
3. install and run the wizard

### Expected Result

should use npm installl --force

What you thought would happen.

### Actual Result
[2024-01-06T13_32_01_505Z-eresolve-report.txt](https://github.com/getsentry/sentry-wizard/files/13849855/2024-01-06T13_32_01_505Z-eresolve-report.txt)

uses npm install and fails the installation because an unrelated package ng-hcaptcha, is throwing a peer dependency error

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by Lms24** [comment]
Hi @windmillcode0 thanks for writing in!

> should use npm installl --force

This is dangerous and we can't do it by default. We make use of `peerDependencies` ourselves (for example in our Angular packages) and we want to avoid forcefully installing the SDK on a project that might not even be in the our supported version range. 

Generally, I agree though that we could enable force installs via an optional CLI argument. I'm going to backlog this for the moment because we can't spend time on feature development for the wizard (we're working on the next major version of the JS SDKs). If you want to take a stab at this yourself feel free to open a PR. I suspect it's not too hard to make this work.

**Comment by Akhil-PITS** [comment]
hi @windmillcode0 ,
Any solution for this? Facing the same here.

Thanks

**Comment by windmillcode0** [comment]
its been working for me now since angular 17.2.0 upgrade your angular? along with sentry make sure its latest version
